[package]
name = "lib_maxwell_mvs"
version = "0.1.0"
authors = ["Artur Sinila <opensource@logarithmus.dev>"]
edition = "2018"

[lib]
name = "lib_maxwell_mvs"

[dependencies]
statrs = "0.13"
rand = "0.7"
plotters = "0.3"
